/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define AHB1ENR     *((uint32_t*)(0x40023830))
#define GPIOD_MODER *((uint32_t*)(0x40020C00))
#define GPIOD_ODR   *((uint32_t*)(0x40020C14))

#define GPIOD_EN 3

#define MODER_OUTPUT(X) 01<<(X*2)

#define LED_RED 14
#define LED_GREEN 12
#define LED_BLUE 15
#define LED_ORANGE 13

void init_leds(){
	AHB1ENR = 1 << GPIOD_EN;
	GPIOD_MODER = MODER_OUTPUT(LED_RED) | MODER_OUTPUT(LED_BLUE)
			| MODER_OUTPUT(LED_GREEN) | MODER_OUTPUT(LED_ORANGE);
}
uint8_t get_string_mod(const char* str){
	uint32_t sum = 0;
	uint8_t i = 0;
	while(str[i] != '\0'){
		sum += (uint8_t)str[i];
		i++;
	}
	return sum%4;
}
uint8_t mod_to_led_pin(uint8_t modValue){
	uint8_t pin = 0;
	switch(modValue){
		case 0:
			pin = LED_RED;
		break;
		case 1:
			pin = LED_BLUE;
		break;
		case 2:
			pin = LED_ORANGE;
		break;
		case 3:
			pin = LED_GREEN;
		break;
		default:
			pin = 0;

		}
	return pin;
}
void turn_led_on(uint8_t modValue){
	uint8_t pin = mod_to_led_pin(modValue);
	GPIOD_ODR |= 1 << pin;
}

void turn_led_off(uint8_t modValue){
	uint8_t pin = mod_to_led_pin(modValue);
	GPIOD_ODR &= ~(1 << pin);
}

void turn_name_on(const char* name){
	uint8_t nameMod = get_string_mod(name);
	turn_led_on(nameMod);
}

void turn_name_off(const char* name){
	uint8_t nameMod = get_string_mod(name);
	turn_led_off(nameMod);
}
//written these functions for sake of completeness
void turn_surname_on(const char* surname){
	uint8_t nameMod = get_string_mod(surname);
	turn_led_on(nameMod);
}
//written these functions for sake of completeness
void turn_surname_off(const char* surname){
	uint8_t nameMod = get_string_mod(surname);
	turn_led_off(nameMod);
}

void delay_fixed(){
	uint32_t i = 0;
	for(i = 0; i < 256*256*256*2; i++);
}

int main(void)
{
    const char name[] = "alican";
    const char surname[] = "ceviker";
    uint8_t nameLen = sizeof(name)/sizeof(char) - 1;
    uint8_t surnameLen = sizeof(name)/sizeof(char) - 1;
    uint8_t  i = 0;
    init_leds();
    for(i = 0; i < nameLen; i++){
    	turn_name_on(name);
    	delay_fixed();
    	turn_name_off(name);
    	delay_fixed();
    }
    for(i = 0; i < surnameLen; i++){
    	turn_surname_on(surname);
       	delay_fixed();
       	turn_surname_off(surname);
       	delay_fixed();
    }
	for(;;);
}
